apiversion: app/v1
kind: Deployment
metadata:
 name: nginx
 #this labels are replecaset labels
 labels:
  purpose: dp-demo
  project: roboshop
spec:
 replicas: 3
 selector:
 # this lablels used to  select the pods
  matchlabels:
   #purpose: dp-demo
   #project: roboshop
   purpose: headless-svc-demo
   project: roboshop
   #pod defention
  templects:
    metadata:
      labels:
      #purpose: dp-demo
      purpose: headless-svc-demo
      project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerport: 80

---
apiversion: v1
kind: services
metadata:
   name: nginx
spec:
 selector:
   purpose: headless-svc-demo
   project: roboshop
ports:
    - protocol: tcp
      port: 80 #services port
      targetport: 80  #containers port
---
apiversion: v1
kind: services
metadata:
   name: nginx-headless
spec:
 clusterip: None
 selector:
   purpose: headless-svc-demo
   project: roboshop
ports:
    - protocol: tcp
      port: 80 #services port
      targetport: 80  #containers port      
